; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non‑commercial use only

#define MyAppName "F HamLog 2"
#define MyAppVersion "2.2.0"
#define MyAppPublisher "木比白桦 BI8SQL"
#define MyAppURL "https://mubi‑baihua.github.io/f_hamlog.html"
#define MyAppExeName "F HamLog 2.2.exe"

[Setup]
AppId={{9C87FCB8‑00FD‑4889‑8E7B‑02B5789015C0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
OutputDir=D:\F-Dev\BIG\F_HamLog\F HamLog 2 Inno Setup
OutputBaseFilename=F HamLog 2.2 setup
SetupIconFile=D:\F-Dev\BIG\F_HamLog\file\F_HamLog.ico
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
;普通程序文件，每次升级正常覆盖，排除file文件夹
Source: "D:\F-Dev\BIG\F_HamLog\main.dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\F-Dev\BIG\F_HamLog\main.dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "file\*"

; file目录：单文件级"存在则保留、缺失则创建（带数据）"
; 不使用 ignoreversion/recursesubdirs，改用 onlyifdoesntexist：
; 仅当目标同名文件不存在时才安装，升级时用户数据不被覆盖，新增模板会自动补回
Source: "D:\F-Dev\BIG\F_HamLog\main.dist\file\amateur.tle"; DestDir: "{app}\file"; Flags: onlyifdoesntexist
Source: "D:\F-Dev\BIG\F_HamLog\main.dist\file\F_HamLog.ico"; DestDir: "{app}\file"; Flags: onlyifdoesntexist
Source: "D:\F-Dev\BIG\F_HamLog\main.dist\file\main.fhl"; DestDir: "{app}\file"; Flags: onlyifdoesntexist
Source: "D:\F-Dev\BIG\F_HamLog\main.dist\file\m_xml.txt"; DestDir: "{app}\file"; Flags: onlyifdoesntexist
Source: "D:\F-Dev\BIG\F_HamLog\main.dist\file\pack_list.txt"; DestDir: "{app}\file"; Flags: onlyifdoesntexist
Source: "D:\F-Dev\BIG\F_HamLog\main.dist\file\sat_radio_dict.txt"; DestDir: "{app}\file"; Flags: onlyifdoesntexist
Source: "D:\F-Dev\BIG\F_HamLog\main.dist\file\tqsl_dict.txt"; DestDir: "{app}\file"; Flags: onlyifdoesntexist
Source: "D:\F-Dev\BIG\F_HamLog\main.dist\file\world_land.json"; DestDir: "{app}\file"; Flags: onlyifdoesntexist

[Dirs]
Name: "{app}\file"; Check: not DirExists(ExpandConstant('{app}\file'))

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon